<?php

/**
 * @file
 * Module file of bt_toolbar module.
 */

//use \Drupal\user\Entity\User;
//use \Drupal\personas\PersonaUtility;

/**
 * Implements hook_toolbar_alter().
 */
function bt_toolbar_toolbar_alter(&$items) {
  $current_user = \Drupal::service('current_user');
  //$user_id = $current_user->id();
  //$user_account = User::load($user_id);

  if (array_key_exists('contextual', $items)) {
    unset($items['contextual']);
  }
  if (array_key_exists('redhen', $items)) {
    unset($items['redhen']);
  }
  if (array_key_exists('user', $items)) {
    unset($items['user']);
  }

  //if (!PersonaUtility::hasPersona($user_account, 'bt_web_admin')){
  //    $items['toolbar_menu_mi_pyme']['#attached']['library'][] = 'admin_toolbar/toolbar.tree';
  //    $items['toolbar_menu_mi_pyme']['#attached']['library'][] = 'bt_toolbar/bt-toolbar';
  //}

  $items['toolbar_menu_my_account']['#weight'] = 2;
  $items['toolbar_menu_my_account']['tab']['#title'] = $current_user->getDisplayName();
  $items['toolbar_menu_my_company']['tab']['#title'] = \Drupal::config('system.site')->get('name');
}
