<?php

/**
 * @file
 * Module file of bt_toolbar module.
 */

/**
 * Implements hook_toolbar_alter().
 */
function bt_toolbar_toolbar_alter(&$items) {
  $current_user = \Drupal::service('current_user');

  if (array_key_exists('contextual', $items)) {
    unset($items['contextual']);
  }
  if (array_key_exists('redhen', $items)) {
    unset($items['redhen']);
  }
  if (array_key_exists('user', $items)) {
    unset($items['user']);
  }

  $items['toolbar_menu_my_account']['#weight'] = 2;
  $items['toolbar_menu_my_account']['tab']['#title'] = $current_user->getDisplayName();
  $items['toolbar_menu_my_company']['tab']['#title'] = \Drupal::config('system.site')->get('name');
}
